package dev.stride.hud

import java.math.BigDecimal
import java.math.RoundingMode
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * [Gpx] against the script it was ported from, on three real walks.
 *
 * The console converts its own routes now, so that adding a `.gpx` to Home
 * Assistant is the whole of adding a route. What it must not do is convert them
 * *differently* from `homeassistant/stride_gpx.py`: the segments coming out of
 * either one are what tilts the deck, and a walk that felt steeper than it did
 * last month with no explanation would be a horrible thing to debug from a
 * treadmill. So the port is held to the original's own output, fact by fact —
 * every segment boundary and gradient, every kept track vertex, every
 * elevation sample.
 *
 * `expected-digest.txt` is generated by `tools/gpx-golden.py` and committed.
 * Regenerating it is a deliberate act with a readable diff; see that script.
 *
 * The three fixtures are real recorded walks, not drawings: between them they
 * exercise the flat-ground quantiser, a route with a hill worth the name, and
 * the point budget at three densities (176, 152 and 98 recorded points). Real
 * matters here — a hand-drawn track has none of the things that break a
 * converter, and all three of these carry repeated vertices where the recorder
 * paused and the metre-scale altitude hash that [Gpx] exists to smooth.
 *
 * They have been **moved**. Every coordinate is offset by a constant, the
 * metadata is stripped and the files are renamed, because this is a public
 * repository and the originals are somebody's neighbourhood. The offset is not
 * recorded anywhere — a recorded offset is a reversible one. Distances differ
 * from the originals because of it and that costs the test nothing: it asks
 * whether two converters agree on the same input, not what the input was.
 */
class GpxTest {

    /** What this board reports, and what the golden was generated against. */
    private val floor = -3.0
    private val ceiling = 15.0

    private fun resource(name: String): ByteArray =
        javaClass.classLoader!!.getResourceAsStream("gpx/$name")
            ?.use { it.readBytes() }
            ?: throw AssertionError("missing test resource gpx/$name")

    private fun n(v: Double, places: Int): String {
        val d = BigDecimal(v).setScale(places, RoundingMode.HALF_EVEN)
        return if (d.signum() == 0) BigDecimal.ZERO.setScale(places).toPlainString()
               else d.toPlainString()
    }

    /** The same facts, in the same order, as tools/gpx-golden.py emits. */
    private fun digest(filename: String, r: Gpx.Route): List<String> {
        val out = ArrayList<String>()
        fun say(vararg parts: Any) =
            out.add((listOf(filename) + parts.map { it.toString() }).joinToString(" "))

        say("id", r.id)
        say("name", r.name)
        say("distance_m", n(r.distanceM, 1))
        say("climb_m", n(r.climbM, 1))
        say("segments", r.segments.size)
        r.segments.forEachIndexed { i, s ->
            say("seg", i, n(s[0], 1), n(s[1], 1), n(s[2], 1))
        }
        say("track", r.track.size)
        r.track.forEachIndexed { i, p ->
            say("tk", i, n(p[0], 6), n(p[1], 6), n(p[2], 1))
        }
        say("elev", r.elev.size)
        r.elev.forEachIndexed { i, p -> say("el", i, n(p[0], 1), n(p[1], 1)) }
        say("bounds", n(r.bounds[0], 6), n(r.bounds[1], 6),
                      n(r.bounds[2], 6), n(r.bounds[3], 6))
        return out
    }

    @Test
    fun `converts the same routes the script does, fact for fact`() {
        val expected = String(resource("expected-digest.txt"))
            .trim().lines().filter { it.isNotBlank() }
        assertTrue("the golden digest is empty — run tools/gpx-golden.py",
                   expected.isNotEmpty())

        // Which files to convert comes out of the golden itself, so adding a
        // fixture is a matter of dropping it in and regenerating.
        val files = expected.map { it.substringBefore(' ') }.distinct()
        val actual = ArrayList<String>()
        for (f in files) {
            actual += digest(f, Gpx.convert(f, resource(f), floor, ceiling))
        }

        // Line by line rather than as two blobs: the first disagreement is the
        // one worth reading, and it names itself —
        //   rolling-loop-5k.gpx seg 7 900.0 1200.0 0.0
        val limit = Math.min(expected.size, actual.size)
        for (i in 0 until limit) {
            assertEquals("line ${i + 1} of the golden digest", expected[i], actual[i])
        }
        assertEquals("number of facts", expected.size, actual.size)
    }

    @Test
    fun `names and ids come from the filename, not the file`() {
        // An exporter's own <name> is "New file 1"; a filename is something
        // somebody chose. The id is the slug, which is why renaming a file
        // replaces the route rather than adding a second copy of it.
        assertEquals("gpx-rolling-loop-5k", Gpx.routeId("rolling-loop-5k.gpx"))
        assertEquals("Rolling loop 5k", Gpx.routeName("rolling-loop-5k.gpx"))
        assertEquals("gpx-three-lap-hill", Gpx.routeId("three-lap-hill.gpx"))
        assertEquals("Three lap hill", Gpx.routeName("three-lap-hill.gpx"))
        // Mixed case and spaces both survive a round trip through the slug.
        assertEquals("gpx-friday-river-loop", Gpx.routeId("Friday River Loop.gpx"))
        assertEquals("Friday River Loop", Gpx.routeName("Friday River Loop.gpx"))
        // Full paths arrive from a folder sensor's file_list; only the base
        // name may reach the slug, or the route id would carry /config/www.
        assertEquals("gpx-the-hill",
                     Gpx.routeId("/config/www/treadmill/routes/the_hill.GPX"))
        assertEquals("The hill",
                     Gpx.routeName("/config/www/treadmill/routes/the_hill.GPX"))
        // Nothing usable left after slugging still has to be a legal id.
        assertEquals("gpx-route", Gpx.routeId("---.gpx"))
        assertEquals("Route", Gpx.routeName("---.gpx"))
    }

    @Test
    fun `refuses what it cannot drive`() {
        // A console that accepted these would offer a walk and then fail at the
        // moment somebody stood on the belt and chose it.
        val noPoints = """<gpx><trk><trkseg></trkseg></trk></gpx>""".toByteArray()
        try {
            Gpx.convert("empty.gpx", noPoints, floor, ceiling)
            throw AssertionError("a GPX with no trackpoints was accepted")
        } catch (e: Gpx.Unusable) {
            assertTrue(e.message!!.contains("trackpoint"))
        }

        // Two points a few metres apart: real, parseable, and not a walk.
        val tiny = ("""<gpx><trk><trkseg>""" +
                """<trkpt lat="40.4" lon="-80.0"><ele>300</ele></trkpt>""" +
                """<trkpt lat="40.4001" lon="-80.0"><ele>301</ele></trkpt>""" +
                """</trkseg></trk></gpx>""").toByteArray()
        try {
            Gpx.convert("tiny.gpx", tiny, floor, ceiling)
            throw AssertionError("an 11 m route was accepted")
        } catch (e: Gpx.Unusable) {
            assertTrue(e.message!!.contains("long"))
        }
    }

    @Test
    fun `reads a namespaced gpx, because every exporter writes a different one`() {
        // Garmin, Strava and Komoot all namespace this differently. The Python
        // matches on the tag suffix; so must this, or a route imports on one
        // machine and not the other.
        val ns = StringBuilder("""<?xml version="1.0"?>""" +
            """<gpx:gpx xmlns:gpx="http://www.topografix.com/GPX/1/1">""" +
            """<gpx:trk><gpx:trkseg>""")
        for (i in 0 until 60) {
            ns.append("""<gpx:trkpt lat="40.${4000 + i * 3}" lon="-80.0">""")
              .append("""<gpx:ele>${300 + i}</gpx:ele></gpx:trkpt>""")
        }
        ns.append("""</gpx:trkseg></gpx:trk></gpx:gpx>""")

        val r = Gpx.convert("Namespaced.gpx", ns.toString().toByteArray(), floor, ceiling)
        assertEquals("Namespaced", r.name)
        assertTrue("a namespaced file produced no ground", r.distanceM > 50)
        assertTrue("a namespaced file produced no segments", r.segments.isNotEmpty())
    }

    /**
     * A stretch too short to be worth moving the deck for is merged backwards.
     *
     * This needed building rather than finding. With a 150 m measuring window,
     * the only segment that can come out shorter than the 120 m minimum is the
     * leftover at the very end — and all three recorded fixtures happen to end
     * with about 50 m left over, which is under any plausible threshold. So
     * mutating MIN_SEGMENT from 120 to 100 changed nothing about them and the
     * golden could not tell the difference: the merge was running, but nothing
     * was testing the number it runs on.
     *
     * 560 m of flat with a steep 110 m on the end puts the tail *between* the
     * two, which is the only place the threshold is visible.
     */
    @Test
    fun `a tail too short to move the deck for is merged into the stretch before it`() {
        // Along the equator, where haversine over a longitude step is just
        // R * dLambda, so the distances below are exact to the millimetre.
        val perMetreDeg = Math.toDegrees(1.0 / 6371008.8)
        val gpx = StringBuilder("<gpx><trk><trkseg>")
        var m = 0
        while (m <= 560) {
            // Flat for 450 m, then 11 m of rise over the last 110 — a 10%
            // tail against 0%, so it cannot merge by being the same gradient
            // and has to be dropped for being too short.
            val ele = if (m <= 450) 100.0 else 100.0 + (m - 450) * 0.10
            gpx.append("<trkpt lat=\"0.0\" lon=\"")
               .append("%.9f".format(m * perMetreDeg))
               .append("\"><ele>").append(ele).append("</ele></trkpt>")
            m += 10
        }
        gpx.append("</trkseg></trk></gpx>")

        val r = Gpx.convert("tail.gpx", gpx.toString().toByteArray(), floor, ceiling)

        // The tail is gone as a segment of its own, and the ground it covered
        // is not: the last segment still reaches the end of the walk.
        assertEquals("the 110 m tail became its own segment", 1, r.segments.size)
        assertEquals("the merged segment does not reach the end of the route",
                     r.distanceM, r.segments.last()[1], 0.05)

        // And the general rule, which is the thing that would actually bite:
        // nothing shorter than the minimum survives, unless the whole route is.
        if (r.segments.size > 1) {
            for (seg in r.segments) {
                assertTrue("a " + (seg[1] - seg[0]) + " m segment survived the merge",
                           seg[1] - seg[0] >= 120.0 - 0.05)
            }
        }
    }

    @Test
    fun `the payload is the shape Routes and the page already read`() {
        val r = Gpx.convert("rolling-loop-5k.gpx",
                            resource("rolling-loop-5k.gpx"), floor, ceiling)
        val json = Gpx.json(listOf(r))

        // The fields the deck and the picker read, spelled as they have always
        // been spelled. A rename here is silent: the page would draw an empty
        // list and Routes.byId would return null.
        for (field in listOf("\"id\"", "\"name\"", "\"distance_m\"", "\"climb_m\"",
                             "\"difficulty\"", "\"segments\"", "\"track\"",
                             "\"elev\"", "\"bounds\"")) {
            assertTrue("$field missing from the payload", json.contains(field))
        }
        // Fixed scales, because this is what a generic serialiser gets wrong:
        // Double.toString is how "5021.400000000001" ends up in a cache file.
        // Whatever the relocated fixture measures, it must arrive at one
        // decimal place rather than at Double.toString's full precision.
        assertTrue("distance lost its scale",
                   Regex("""\"distance_m\":\d+\.\d""").containsMatchIn(json))
        assertTrue("difficulty is not the literal the script writes",
                   json.contains("\"difficulty\":1.0"))
        assertTrue("a float crept out at full precision",
                   !Regex("""\d\.\d{8,}""").containsMatchIn(json))

        // An empty list is a legal payload and must not be "" — Routes.accept
        // treats a blank as [] but should never have to.
        assertEquals("[]", Gpx.json(emptyList()))
    }
}
